## Selecting columns

In [13]:
import pandas as pd

In [14]:
df = pd.read_csv("data.csv")

In [15]:
df

,Actor,Film,Year,Genre,Boxoffice (Cr),IMDb
0,Aamir Khan,PK,2014,Comedy/Sci-Fi,750,8.1
1,Salman Khan,Bajrangi Bhaijaan,2015,Drama/Action,922,8.1
2,Shah Rukh Khan,Jawan,2023,Action/Thriller,1148,7.0
3,Ranbir Kapoor,Animal,2023,Action/Drama,917,6.3
4,Vicky Kaushal,Chhaava,2025,Historical/Drama,808,7.3
5,Rajkummar Rao,Stree 2,2024,Horror/Comedy,852,6.9
6,Sunny Deol,Gadar 2,2023,Action/Drama,691,5.1
7,Ranbir Kapoor,Sanju,2018,Biography,586,7.6
8,Salman Khan,Sultan,2016,Sports/Drama,615,7.1
9,Hrithik Roshan,War,2019,Action/Thriller,475,6.5
10,Shahid Kapoor,Kabir Singh,2019,Romance/Drama,379,7.0
11,Akshay Kumar,Mission Mangal,2019,Drama/Sci-Fi,290,7.1
12,Ajay Devgn,Tanhaji,2020,Historical/Action,367,7.5
13,Ranveer Singh,Simmba,2018,Action/Comedy,400,5.8
14,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror/Comedy,266,6.8
15,Varun Dhawan,Judwaa 2,2017,Comedy/Action,227,3.6
16,Alia Bhatt,Raazi,2018,Thriller/Drama,195,7.7
17,Akshay Kumar,Toilet: Ek Prem Katha,2017,Drama/Comedy,311,7.2
18,Ayushmann Khurrana,Badhaai Ho,2018,Comedy/Drama,221,7.9
19,Tiger Shroff,Baaghi 2,2018,Action/Thriller,254,4.8
20,Shah Rukh Khan,Chennai Express,2013,Action/Comedy,423,6.0
21,Salman Khan,Kick,2014,Action/Comedy,402,5.3
22,Hrithik Roshan,Krrish 3,2013,Superhero,393,5.3
23,Aamir Khan,Dhoom 3,2013,Action/Thriller,556,5.4
24,Ranbir Kapoor,Yeh Jawaani Hai Deewani,2013,Romance/Drama,319,7.2
25,Sidharth Malhotra,Ek Villain,2014,Action/Thriller,153,6.5
26,Varun Dhawan,Badrinath Ki Dulhania,2017,Romance/Comedy,201,6.1
27,Ajay Devgn,Singham Returns,2014,Action/Drama,216,5.7
28,Akshay Kumar,Airlift,2016,Thriller/Drama,231,7.9
29,Ranveer Singh,Bajirao Mastani,2015,Historical/Romance,354,7.2
30,Amitabh Bachchan,Piku,2015,Comedy/Drama,141,7.6
31,Kangana Ranaut,Queen,2013,Comedy/Drama,108,8.1
32,Sushant Singh Rajput,M.S. Dhoni: The Untold Story,2016,Biography/Sports,216,7.9
33,Akshay Kumar,Rustom,2016,Crime/Thriller,218,7.0
34,Ajay Devgn,Drishyam,2015,Crime/Thriller,110,8.2
35,Varun Dhawan,Badlapur,2015,Action/Crime,81,7.4
36,Salman Khan,Prem Ratan Dhan Payo,2015,Drama/Romance,405,4.4
37,Shah Rukh Khan,Dilwale,2015,Action/Comedy,388,5.1
38,Akshay Kumar,Good Newwz,2019,Comedy/Drama,318,6.9
39,Ayushmann Khurrana,Dream Girl,2019,Comedy,200,7.0
40,Shahid Kapoor,Haider,2014,Crime/Drama,95,8.0
41,Ranveer Singh,Gully Boy,2019,Musical/Drama,238,7.9
42,Hrithik Roshan,Super 30,2019,Biography/Drama,208,7.9
43,Vicky Kaushal,Raazi,2018,Action/Thriller,195,7.7
44,Salman Khan,Bharat,2019,Action/Drama,325,4.8
45,Ajay Devgn,Raid,2018,Crime/Drama,153,7.4
46,Akshay Kumar,Pad Man,2018,Biography/Drama,207,7.9
47,Amitabh Bachchan,Pink,2016,Drama/Thriller,107,8.1
48,Ranbir Kapoor,Barfi!,2012,Comedy/Drama,175,8.1
49,Aamir Khan,3 Idiots,2009,Comedy/Drama,400,8.4

In [16]:
df['Actor']

0               Aamir Khan
1              Salman Khan
2           Shah Rukh Khan
3            Ranbir Kapoor
4            Vicky Kaushal
5            Rajkummar Rao
6               Sunny Deol
7            Ranbir Kapoor
8              Salman Khan
9           Hrithik Roshan
10           Shahid Kapoor
11            Akshay Kumar
12              Ajay Devgn
13           Ranveer Singh
14           Kartik Aaryan
15            Varun Dhawan
16              Alia Bhatt
17            Akshay Kumar
18      Ayushmann Khurrana
19            Tiger Shroff
20          Shah Rukh Khan
21             Salman Khan
22          Hrithik Roshan
23              Aamir Khan
24           Ranbir Kapoor
25       Sidharth Malhotra
26            Varun Dhawan
27              Ajay Devgn
28            Akshay Kumar
29           Ranveer Singh
30        Amitabh Bachchan
31          Kangana Ranaut
32    Sushant Singh Rajput
33            Akshay Kumar
34              Ajay Devgn
35            Varun Dhawan
36             Salman Khan
37          Shah Rukh Khan
38            Akshay Kumar
39      Ayushmann Khurrana
40           Shahid Kapoor
41           Ranveer Singh
42          Hrithik Roshan
43           Vicky Kaushal
44             Salman Khan
45              Ajay Devgn
46            Akshay Kumar
47        Amitabh Bachchan
48           Ranbir Kapoor
49              Aamir Khan
Name: Actor, dtype: object

In [17]:
df[["Actor","Film"]]

                   Actor                          Film
0             Aamir Khan                            PK
1            Salman Khan             Bajrangi Bhaijaan
2         Shah Rukh Khan                         Jawan
3          Ranbir Kapoor                        Animal
4          Vicky Kaushal                       Chhaava
5          Rajkummar Rao                       Stree 2
6             Sunny Deol                       Gadar 2
7          Ranbir Kapoor                         Sanju
8            Salman Khan                        Sultan
9         Hrithik Roshan                           War
10         Shahid Kapoor                   Kabir Singh
11          Akshay Kumar                Mission Mangal
12            Ajay Devgn                       Tanhaji
13         Ranveer Singh                        Simmba
14         Kartik Aaryan             Bhool Bhulaiyaa 2
15          Varun Dhawan                      Judwaa 2
16            Alia Bhatt                         Raazi
17          Akshay Kumar         Toilet: Ek Prem Katha
18    Ayushmann Khurrana                    Badhaai Ho
19          Tiger Shroff                      Baaghi 2
20        Shah Rukh Khan               Chennai Express
21           Salman Khan                          Kick
22        Hrithik Roshan                      Krrish 3
23            Aamir Khan                       Dhoom 3
24         Ranbir Kapoor       Yeh Jawaani Hai Deewani
25     Sidharth Malhotra                    Ek Villain
26          Varun Dhawan         Badrinath Ki Dulhania
27            Ajay Devgn               Singham Returns
28          Akshay Kumar                       Airlift
29         Ranveer Singh               Bajirao Mastani
30      Amitabh Bachchan                          Piku
31        Kangana Ranaut                         Queen
32  Sushant Singh Rajput  M.S. Dhoni: The Untold Story
33          Akshay Kumar                        Rustom
34            Ajay Devgn                      Drishyam
35          Varun Dhawan                      Badlapur
36           Salman Khan          Prem Ratan Dhan Payo
37        Shah Rukh Khan                       Dilwale
38          Akshay Kumar                    Good Newwz
39    Ayushmann Khurrana                    Dream Girl
40         Shahid Kapoor                        Haider
41         Ranveer Singh                     Gully Boy
42        Hrithik Roshan                      Super 30
43         Vicky Kaushal                         Raazi
44           Salman Khan                        Bharat
45            Ajay Devgn                          Raid
46          Akshay Kumar                       Pad Man
47      Amitabh Bachchan                          Pink
48         Ranbir Kapoor                        Barfi!
49            Aamir Khan                      3 Idiots

In [18]:
df.loc[4] # row by label

Actor                Vicky Kaushal
Film                       Chhaava
Year                          2025
Genre             Historical/Drama
Boxoffice (Cr)                 808
IMDb                           7.3
Name: 4, dtype: object

In [19]:
df.iloc[4] # Row by position

Actor                Vicky Kaushal
Film                       Chhaava
Year                          2025
Genre             Historical/Drama
Boxoffice (Cr)                 808
IMDb                           7.3
Name: 4, dtype: object

In [20]:
df.loc[0, "Actor"]        # Value at row 0, column 'Name'

'Aamir Khan'

In [21]:
df.iloc[0, 1]            # Value at row 0, column at index 1

'PK'

In [22]:
df.loc[0:3, ["Actor" ,"Film", "IMDb"]]

            Actor               Film  IMDb
0      Aamir Khan                 PK   8.1
1     Salman Khan  Bajrangi Bhaijaan   8.1
2  Shah Rukh Khan              Jawan   7.0
3   Ranbir Kapoor             Animal   6.3

In [23]:
df.at[0, "Actor"]       # Fast label-based access

'Aamir Khan'

In [24]:
df.iat[0, 1]           # Fast position-based access

'PK'

## Filtering with Conditions

### Simple Condition

In [26]:
df[df["IMDb"] > 8.0]

,Actor,Film,Year,Genre,Boxoffice (Cr),IMDb
0,Aamir Khan,PK,2014,Comedy/Sci-Fi,750,8.1
1,Salman Khan,Bajrangi Bhaijaan,2015,Drama/Action,922,8.1
31,Kangana Ranaut,Queen,2013,Comedy/Drama,108,8.1
34,Ajay Devgn,Drishyam,2015,Crime/Thriller,110,8.2
47,Amitabh Bachchan,Pink,2016,Drama/Thriller,107,8.1
48,Ranbir Kapoor,Barfi!,2012,Comedy/Drama,175,8.1
49,Aamir Khan,3 Idiots,2009,Comedy/Drama,400,8.4

## Multiple Conditions (AND / OR)

In [31]:
df[(df["Year"] > 2018) & (df["Genre"] == "Action/Drama")]

            Actor     Film  Year         Genre  Boxoffice (Cr)  IMDb
3   Ranbir Kapoor   Animal  2023  Action/Drama             917   6.3
6      Sunny Deol  Gadar 2  2023  Action/Drama             691   5.1
44    Salman Khan   Bharat  2019  Action/Drama             325   4.8

In [34]:
df[(df["Year"] == 2018) | (df["IMDb"] < 5.0)]

,Actor,Film,Year,Genre,Boxoffice (Cr),IMDb
7,Ranbir Kapoor,Sanju,2018,Biography,586,7.6
13,Ranveer Singh,Simmba,2018,Action/Comedy,400,5.8
15,Varun Dhawan,Judwaa 2,2017,Comedy/Action,227,3.6
16,Alia Bhatt,Raazi,2018,Thriller/Drama,195,7.7
18,Ayushmann Khurrana,Badhaai Ho,2018,Comedy/Drama,221,7.9
19,Tiger Shroff,Baaghi 2,2018,Action/Thriller,254,4.8
36,Salman Khan,Prem Ratan Dhan Payo,2015,Drama/Romance,405,4.4
43,Vicky Kaushal,Raazi,2018,Action/Thriller,195,7.7
44,Salman Khan,Bharat,2019,Action/Drama,325,4.8
45,Ajay Devgn,Raid,2018,Crime/Drama,153,7.4
46,Akshay Kumar,Pad Man,2018,Biography/Drama,207,7.9

In [42]:
df.query("Year > 2018 and IMDb >= 7.0" )

,Actor,Film,Year,Genre,Boxoffice (Cr),IMDb
2,Shah Rukh Khan,Jawan,2023,Action/Thriller,1148,7.0
4,Vicky Kaushal,Chhaava,2025,Historical/Drama,808,7.3
10,Shahid Kapoor,Kabir Singh,2019,Romance/Drama,379,7.0
11,Akshay Kumar,Mission Mangal,2019,Drama/Sci-Fi,290,7.1
12,Ajay Devgn,Tanhaji,2020,Historical/Action,367,7.5
39,Ayushmann Khurrana,Dream Girl,2019,Comedy,200,7.0
41,Ranveer Singh,Gully Boy,2019,Musical/Drama,238,7.9
42,Hrithik Roshan,Super 30,2019,Biography/Drama,208,7.9