# Handling Missing Values

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data_cleaning_sample.csv")

In [10]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

### Check for Missing Data

In [4]:
 df.isnull()

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [5]:
df.isnull().sum() # count missing per column

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [6]:
df.dropna()

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [8]:
df.dropna(axis=1) # jis column me missing value hogi us column ko drop kar dega

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

In [9]:
df.fillna(0)  # Replace NaN with 0

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5        0  28.0        Delhi      F     eve@domain.com           0
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   0.0        Delhi      M    charlie@example  20-07-2021

In [11]:
df["Age"].fillna(df["Age"].mean()) # null ko replace kar dega mean se

0    25.000000
1    25.833333
2    30.000000
3    25.833333
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    25.833333
Name: Age, dtype: float64

In [13]:
df.ffill()  # forword fill

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [14]:
df.bfill() # backword fill

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

## Detecting & Removing Duplicates

In [16]:
df.duplicated()  # true return karega duplicate pane per

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [17]:
df.drop_duplicates()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

In [19]:
df.duplicated(subset=["Name", "Age"]) # perticuler jagah per search karega jaise Name Aur Age bola hia isme

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

## String Operations with .str

In [20]:
df["Name"].str.lower() # Converts all names to lowercase.

0      alice
1    charlie
2        bob
3    charlie
4      david
5        NaN
6      alice
7      alice
8    charlie
Name: Name, dtype: object

In [22]:
df["City"].str.contains("delhi", case=False) # delhi city rahegi to true return karega

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7    False
8     True
Name: City, dtype: bool

In [24]:
df["Email"].str.split("@")

0    [alice, example.com]
1      [charlie, example]
2      [bob, example.com]
3      [charlie, example]
4    [david, example.com]
5       [eve, domain.com]
6    [alice, example.com]
7    [alice, example.com]
8      [charlie, example]
Name: Email, dtype: object

In [26]:
type(df["Email"].str.split("@"))

pandas.core.series.Series

In [30]:
df2 = df.dropna()

In [31]:
df2

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [41]:
df["Age Group"] = df["Age"].apply(lambda x: "Adult" if x>= 25 else "Minor")

In [42]:
df

      Name   Age         City Gender              Email   Join Date Age Group
0    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020     Adult
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor
4    David  22.0       Mumbai      M  david@example.com  12-11-2019     Minor
5      NaN  28.0        Delhi      F     eve@domain.com         NaN     Adult
6    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
7    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor

In [43]:
gender_map = {"M" : "Male", "F": "Female"}
df["Gender"] = df["Gender"].map(gender_map)

In [44]:
df

      Name   Age         City  Gender              Email   Join Date Age Group
0    Alice  25.0     New York  Female  alice@example.com  01-05-2021     Adult
1  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021     Minor
2      Bob  30.0  Los Angeles    Male    bob@example.com  15-06-2020     Adult
3  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021     Minor
4    David  22.0       Mumbai    Male  david@example.com  12-11-2019     Minor
5      NaN  28.0        Delhi  Female     eve@domain.com         NaN     Adult
6    Alice  25.0     New York  Female  alice@example.com  01-05-2021     Adult
7    Alice  25.0     New York  Female  alice@example.com  01-05-2021     Adult
8  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021     Minor

In [45]:
df["City"].replace({"Delhi": "New Delhi", "Mumbai": "New Mumbai"})

0       New York
1      New Delhi
2    Los Angeles
3      New Delhi
4     New Mumbai
5      New Delhi
6       New York
7       New York
8      New Delhi
Name: City, dtype: object