In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("data.csv")
df

,Actor,Film,Year,Genre,Boxoffice (Cr),IMDb
0,Aamir Khan,PK,2014,Comedy/Sci-Fi,750,8.1
1,Salman Khan,Bajrangi Bhaijaan,2015,Drama/Action,922,8.1
2,Shah Rukh Khan,Jawan,2023,Action/Thriller,1148,7.0
3,Ranbir Kapoor,Animal,2023,Action/Drama,917,6.3
4,Vicky Kaushal,Chhaava,2025,Historical/Drama,808,7.3
5,Rajkummar Rao,Stree 2,2024,Horror/Comedy,852,6.9
6,Sunny Deol,Gadar 2,2023,Action/Drama,691,5.1
7,Ranbir Kapoor,Sanju,2018,Biography,586,7.6
8,Salman Khan,Sultan,2016,Sports/Drama,615,7.1
9,Hrithik Roshan,War,2019,Action/Thriller,475,6.5
10,Shahid Kapoor,Kabir Singh,2019,Romance/Drama,379,7.0
11,Akshay Kumar,Mission Mangal,2019,Drama/Sci-Fi,290,7.1
12,Ajay Devgn,Tanhaji,2020,Historical/Action,367,7.5
13,Ranveer Singh,Simmba,2018,Action/Comedy,400,5.8
14,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror/Comedy,266,6.8
15,Varun Dhawan,Judwaa 2,2017,Comedy/Action,227,3.6
16,Alia Bhatt,Raazi,2018,Thriller/Drama,195,7.7
17,Akshay Kumar,Toilet: Ek Prem Katha,2017,Drama/Comedy,311,7.2
18,Ayushmann Khurrana,Badhaai Ho,2018,Comedy/Drama,221,7.9

# Sorting & Ranking

### Sort by value

In [10]:
df.sort_values("Year")    # Ascending sort

,Actor,Film,Year,Genre,Boxoffice (Cr),IMDb
0,Aamir Khan,PK,2014,Comedy/Sci-Fi,750,8.1
1,Salman Khan,Bajrangi Bhaijaan,2015,Drama/Action,922,8.1
8,Salman Khan,Sultan,2016,Sports/Drama,615,7.1
15,Varun Dhawan,Judwaa 2,2017,Comedy/Action,227,3.6
17,Akshay Kumar,Toilet: Ek Prem Katha,2017,Drama/Comedy,311,7.2
16,Alia Bhatt,Raazi,2018,Thriller/Drama,195,7.7
13,Ranveer Singh,Simmba,2018,Action/Comedy,400,5.8
18,Ayushmann Khurrana,Badhaai Ho,2018,Comedy/Drama,221,7.9
7,Ranbir Kapoor,Sanju,2018,Biography,586,7.6
10,Shahid Kapoor,Kabir Singh,2019,Romance/Drama,379,7.0
11,Akshay Kumar,Mission Mangal,2019,Drama/Sci-Fi,290,7.1
9,Hrithik Roshan,War,2019,Action/Thriller,475,6.5
12,Ajay Devgn,Tanhaji,2020,Historical/Action,367,7.5
14,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror/Comedy,266,6.8
6,Sunny Deol,Gadar 2,2023,Action/Drama,691,5.1
3,Ranbir Kapoor,Animal,2023,Action/Drama,917,6.3
2,Shah Rukh Khan,Jawan,2023,Action/Thriller,1148,7.0
5,Rajkummar Rao,Stree 2,2024,Horror/Comedy,852,6.9
4,Vicky Kaushal,Chhaava,2025,Historical/Drama,808,7.3

In [11]:
df.sort_values("Year", ascending=False)  # decending

,Actor,Film,Year,Genre,Boxoffice (Cr),IMDb
4,Vicky Kaushal,Chhaava,2025,Historical/Drama,808,7.3
5,Rajkummar Rao,Stree 2,2024,Horror/Comedy,852,6.9
2,Shah Rukh Khan,Jawan,2023,Action/Thriller,1148,7.0
3,Ranbir Kapoor,Animal,2023,Action/Drama,917,6.3
6,Sunny Deol,Gadar 2,2023,Action/Drama,691,5.1
14,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror/Comedy,266,6.8
12,Ajay Devgn,Tanhaji,2020,Historical/Action,367,7.5
9,Hrithik Roshan,War,2019,Action/Thriller,475,6.5
10,Shahid Kapoor,Kabir Singh,2019,Romance/Drama,379,7.0
11,Akshay Kumar,Mission Mangal,2019,Drama/Sci-Fi,290,7.1
16,Alia Bhatt,Raazi,2018,Thriller/Drama,195,7.7
13,Ranveer Singh,Simmba,2018,Action/Comedy,400,5.8
18,Ayushmann Khurrana,Badhaai Ho,2018,Comedy/Drama,221,7.9
7,Ranbir Kapoor,Sanju,2018,Biography,586,7.6
15,Varun Dhawan,Judwaa 2,2017,Comedy/Action,227,3.6
17,Akshay Kumar,Toilet: Ek Prem Katha,2017,Drama/Comedy,311,7.2
8,Salman Khan,Sultan,2016,Sports/Drama,615,7.1
1,Salman Khan,Bajrangi Bhaijaan,2015,Drama/Action,922,8.1
0,Aamir Khan,PK,2014,Comedy/Sci-Fi,750,8.1

In [13]:
df.sort_values(["Year", "IMDb"])

,Actor,Film,Year,Genre,Boxoffice (Cr),IMDb
0,Aamir Khan,PK,2014,Comedy/Sci-Fi,750,8.1
1,Salman Khan,Bajrangi Bhaijaan,2015,Drama/Action,922,8.1
8,Salman Khan,Sultan,2016,Sports/Drama,615,7.1
15,Varun Dhawan,Judwaa 2,2017,Comedy/Action,227,3.6
17,Akshay Kumar,Toilet: Ek Prem Katha,2017,Drama/Comedy,311,7.2
13,Ranveer Singh,Simmba,2018,Action/Comedy,400,5.8
7,Ranbir Kapoor,Sanju,2018,Biography,586,7.6
16,Alia Bhatt,Raazi,2018,Thriller/Drama,195,7.7
18,Ayushmann Khurrana,Badhaai Ho,2018,Comedy/Drama,221,7.9
9,Hrithik Roshan,War,2019,Action/Thriller,475,6.5
10,Shahid Kapoor,Kabir Singh,2019,Romance/Drama,379,7.0
11,Akshay Kumar,Mission Mangal,2019,Drama/Sci-Fi,290,7.1
12,Ajay Devgn,Tanhaji,2020,Historical/Action,367,7.5
14,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror/Comedy,266,6.8
6,Sunny Deol,Gadar 2,2023,Action/Drama,691,5.1
3,Ranbir Kapoor,Animal,2023,Action/Drama,917,6.3
2,Shah Rukh Khan,Jawan,2023,Action/Thriller,1148,7.0
5,Rajkummar Rao,Stree 2,2024,Horror/Comedy,852,6.9
4,Vicky Kaushal,Chhaava,2025,Historical/Drama,808,7.3

In [23]:
df2 = df.sort_values(["Year", "IMDb"])

In [25]:
df2

,Actor,Film,Year,Genre,Boxoffice (Cr),IMDb
0,Aamir Khan,PK,2014,Comedy/Sci-Fi,750,8.1
1,Salman Khan,Bajrangi Bhaijaan,2015,Drama/Action,922,8.1
8,Salman Khan,Sultan,2016,Sports/Drama,615,7.1
15,Varun Dhawan,Judwaa 2,2017,Comedy/Action,227,3.6
17,Akshay Kumar,Toilet: Ek Prem Katha,2017,Drama/Comedy,311,7.2
13,Ranveer Singh,Simmba,2018,Action/Comedy,400,5.8
7,Ranbir Kapoor,Sanju,2018,Biography,586,7.6
16,Alia Bhatt,Raazi,2018,Thriller/Drama,195,7.7
18,Ayushmann Khurrana,Badhaai Ho,2018,Comedy/Drama,221,7.9
9,Hrithik Roshan,War,2019,Action/Thriller,475,6.5
10,Shahid Kapoor,Kabir Singh,2019,Romance/Drama,379,7.0
11,Akshay Kumar,Mission Mangal,2019,Drama/Sci-Fi,290,7.1
12,Ajay Devgn,Tanhaji,2020,Historical/Action,367,7.5
14,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror/Comedy,266,6.8
6,Sunny Deol,Gadar 2,2023,Action/Drama,691,5.1
3,Ranbir Kapoor,Animal,2023,Action/Drama,917,6.3
2,Shah Rukh Khan,Jawan,2023,Action/Thriller,1148,7.0
5,Rajkummar Rao,Stree 2,2024,Horror/Comedy,852,6.9
4,Vicky Kaushal,Chhaava,2025,Historical/Drama,808,7.3

### Reset Index

In [50]:
df2.reset_index(drop=True, inplace=True)

### sort by index

In [51]:
df2.sort_index()

,index,Actor,Film,Year,Genre,Boxoffice (Cr),IMDb,Rank
0,0,Aamir Khan,PK,2014,Comedy/Sci-Fi,750,8.1,16.0
1,1,Salman Khan,Bajrangi Bhaijaan,2015,Drama/Action,922,8.1,16.0
2,2,Salman Khan,Sultan,2016,Sports/Drama,615,7.1,8.0
3,3,Varun Dhawan,Judwaa 2,2017,Comedy/Action,227,3.6,4.0
4,4,Akshay Kumar,Toilet: Ek Prem Katha,2017,Drama/Comedy,311,7.2,11.0
5,5,Ranveer Singh,Simmba,2018,Action/Comedy,400,5.8,7.0
6,6,Ranbir Kapoor,Sanju,2018,Biography,586,7.6,2.0
7,7,Alia Bhatt,Raazi,2018,Thriller/Drama,195,7.7,13.0
8,8,Ayushmann Khurrana,Badhaai Ho,2018,Comedy/Drama,221,7.9,9.0
9,9,Hrithik Roshan,War,2019,Action/Thriller,475,6.5,5.0
10,10,Shahid Kapoor,Kabir Singh,2019,Romance/Drama,379,7.0,8.0
11,11,Akshay Kumar,Mission Mangal,2019,Drama/Sci-Fi,290,7.1,9.0
12,12,Ajay Devgn,Tanhaji,2020,Historical/Action,367,7.5,12.0
13,13,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror/Comedy,266,6.8,3.0
14,14,Sunny Deol,Gadar 2,2023,Action/Drama,691,5.1,6.0
15,15,Ranbir Kapoor,Animal,2023,Action/Drama,917,6.3,1.0
16,16,Shah Rukh Khan,Jawan,2023,Action/Thriller,1148,7.0,14.0
17,17,Rajkummar Rao,Stree 2,2024,Horror/Comedy,852,6.9,10.0
18,18,Vicky Kaushal,Chhaava,2025,Historical/Drama,808,7.3,15.0

In [52]:
df2["Rank"] = df["IMDb"].rank()  # average me rank karega

In [53]:
df2

,index,Actor,Film,Year,Genre,Boxoffice (Cr),IMDb,Rank
0,0,Aamir Khan,PK,2014,Comedy/Sci-Fi,750,8.1,18.5
1,1,Salman Khan,Bajrangi Bhaijaan,2015,Drama/Action,922,8.1,18.5
2,2,Salman Khan,Sultan,2016,Sports/Drama,615,7.1,8.5
3,3,Varun Dhawan,Judwaa 2,2017,Comedy/Action,227,3.6,4.0
4,4,Akshay Kumar,Toilet: Ek Prem Katha,2017,Drama/Comedy,311,7.2,13.0
5,5,Ranveer Singh,Simmba,2018,Action/Comedy,400,5.8,7.0
6,6,Ranbir Kapoor,Sanju,2018,Biography,586,7.6,2.0
7,7,Alia Bhatt,Raazi,2018,Thriller/Drama,195,7.7,15.0
8,8,Ayushmann Khurrana,Badhaai Ho,2018,Comedy/Drama,221,7.9,10.5
9,9,Hrithik Roshan,War,2019,Action/Thriller,475,6.5,5.0
10,10,Shahid Kapoor,Kabir Singh,2019,Romance/Drama,379,7.0,8.5
11,11,Akshay Kumar,Mission Mangal,2019,Drama/Sci-Fi,290,7.1,10.5
12,12,Ajay Devgn,Tanhaji,2020,Historical/Action,367,7.5,14.0
13,13,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror/Comedy,266,6.8,3.0
14,14,Sunny Deol,Gadar 2,2023,Action/Drama,691,5.1,6.0
15,15,Ranbir Kapoor,Animal,2023,Action/Drama,917,6.3,1.0
16,16,Shah Rukh Khan,Jawan,2023,Action/Thriller,1148,7.0,16.0
17,17,Rajkummar Rao,Stree 2,2024,Horror/Comedy,852,6.9,12.0
18,18,Vicky Kaushal,Chhaava,2025,Historical/Drama,808,7.3,17.0

In [54]:
df2["Rank"] = df["IMDb"].rank(method="dense")  # float me nhi rank karega

In [55]:
df2

,index,Actor,Film,Year,Genre,Boxoffice (Cr),IMDb,Rank
0,0,Aamir Khan,PK,2014,Comedy/Sci-Fi,750,8.1,16.0
1,1,Salman Khan,Bajrangi Bhaijaan,2015,Drama/Action,922,8.1,16.0
2,2,Salman Khan,Sultan,2016,Sports/Drama,615,7.1,8.0
3,3,Varun Dhawan,Judwaa 2,2017,Comedy/Action,227,3.6,4.0
4,4,Akshay Kumar,Toilet: Ek Prem Katha,2017,Drama/Comedy,311,7.2,11.0
5,5,Ranveer Singh,Simmba,2018,Action/Comedy,400,5.8,7.0
6,6,Ranbir Kapoor,Sanju,2018,Biography,586,7.6,2.0
7,7,Alia Bhatt,Raazi,2018,Thriller/Drama,195,7.7,13.0
8,8,Ayushmann Khurrana,Badhaai Ho,2018,Comedy/Drama,221,7.9,9.0
9,9,Hrithik Roshan,War,2019,Action/Thriller,475,6.5,5.0
10,10,Shahid Kapoor,Kabir Singh,2019,Romance/Drama,379,7.0,8.0
11,11,Akshay Kumar,Mission Mangal,2019,Drama/Sci-Fi,290,7.1,9.0
12,12,Ajay Devgn,Tanhaji,2020,Historical/Action,367,7.5,12.0
13,13,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror/Comedy,266,6.8,3.0
14,14,Sunny Deol,Gadar 2,2023,Action/Drama,691,5.1,6.0
15,15,Ranbir Kapoor,Animal,2023,Action/Drama,917,6.3,1.0
16,16,Shah Rukh Khan,Jawan,2023,Action/Thriller,1148,7.0,14.0
17,17,Rajkummar Rao,Stree 2,2024,Horror/Comedy,852,6.9,10.0
18,18,Vicky Kaushal,Chhaava,2025,Historical/Drama,808,7.3,15.0

In [58]:
df2.rename(columns={"Boxoffice (Cr)" : "Boxoffice (Crore)"}, inplace=True)

In [59]:
df2

,index,Actor,Film,Year,Genre,Boxoffice (Crore),IMDb,Rank
0,0,Aamir Khan,PK,2014,Comedy/Sci-Fi,750,8.1,16.0
1,1,Salman Khan,Bajrangi Bhaijaan,2015,Drama/Action,922,8.1,16.0
2,2,Salman Khan,Sultan,2016,Sports/Drama,615,7.1,8.0
3,3,Varun Dhawan,Judwaa 2,2017,Comedy/Action,227,3.6,4.0
4,4,Akshay Kumar,Toilet: Ek Prem Katha,2017,Drama/Comedy,311,7.2,11.0
5,5,Ranveer Singh,Simmba,2018,Action/Comedy,400,5.8,7.0
6,6,Ranbir Kapoor,Sanju,2018,Biography,586,7.6,2.0
7,7,Alia Bhatt,Raazi,2018,Thriller/Drama,195,7.7,13.0
8,8,Ayushmann Khurrana,Badhaai Ho,2018,Comedy/Drama,221,7.9,9.0
9,9,Hrithik Roshan,War,2019,Action/Thriller,475,6.5,5.0
10,10,Shahid Kapoor,Kabir Singh,2019,Romance/Drama,379,7.0,8.0
11,11,Akshay Kumar,Mission Mangal,2019,Drama/Sci-Fi,290,7.1,9.0
12,12,Ajay Devgn,Tanhaji,2020,Historical/Action,367,7.5,12.0
13,13,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror/Comedy,266,6.8,3.0
14,14,Sunny Deol,Gadar 2,2023,Action/Drama,691,5.1,6.0
15,15,Ranbir Kapoor,Animal,2023,Action/Drama,917,6.3,1.0
16,16,Shah Rukh Khan,Jawan,2023,Action/Thriller,1148,7.0,14.0
17,17,Rajkummar Rao,Stree 2,2024,Horror/Comedy,852,6.9,10.0
18,18,Vicky Kaushal,Chhaava,2025,Historical/Drama,808,7.3,15.0

### To rename all columns

In [65]:
df2.columns = [ "index","actor", "film", "saal" , "gener","eraning", "IMDB","Ranking"]

In [66]:
df2

,index,actor,film,saal,gener,eraning,IMDB,Ranking
0,0,Aamir Khan,PK,2014,Comedy/Sci-Fi,750,8.1,16.0
1,1,Salman Khan,Bajrangi Bhaijaan,2015,Drama/Action,922,8.1,16.0
2,2,Salman Khan,Sultan,2016,Sports/Drama,615,7.1,8.0
3,3,Varun Dhawan,Judwaa 2,2017,Comedy/Action,227,3.6,4.0
4,4,Akshay Kumar,Toilet: Ek Prem Katha,2017,Drama/Comedy,311,7.2,11.0
5,5,Ranveer Singh,Simmba,2018,Action/Comedy,400,5.8,7.0
6,6,Ranbir Kapoor,Sanju,2018,Biography,586,7.6,2.0
7,7,Alia Bhatt,Raazi,2018,Thriller/Drama,195,7.7,13.0
8,8,Ayushmann Khurrana,Badhaai Ho,2018,Comedy/Drama,221,7.9,9.0
9,9,Hrithik Roshan,War,2019,Action/Thriller,475,6.5,5.0
10,10,Shahid Kapoor,Kabir Singh,2019,Romance/Drama,379,7.0,8.0
11,11,Akshay Kumar,Mission Mangal,2019,Drama/Sci-Fi,290,7.1,9.0
12,12,Ajay Devgn,Tanhaji,2020,Historical/Action,367,7.5,12.0
13,13,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror/Comedy,266,6.8,3.0
14,14,Sunny Deol,Gadar 2,2023,Action/Drama,691,5.1,6.0
15,15,Ranbir Kapoor,Animal,2023,Action/Drama,917,6.3,1.0
16,16,Shah Rukh Khan,Jawan,2023,Action/Thriller,1148,7.0,14.0
17,17,Rajkummar Rao,Stree 2,2024,Horror/Comedy,852,6.9,10.0
18,18,Vicky Kaushal,Chhaava,2025,Historical/Drama,808,7.3,15.0

## Changing Column Order

In [69]:
df2 = df2[[ "index","film", "actor", "gener" , "saal","eraning", "IMDB","Ranking"]] #Reorder as desires
df2

,index,film,actor,gener,saal,eraning,IMDB,Ranking
0,0,PK,Aamir Khan,Comedy/Sci-Fi,2014,750,8.1,16.0
1,1,Bajrangi Bhaijaan,Salman Khan,Drama/Action,2015,922,8.1,16.0
2,2,Sultan,Salman Khan,Sports/Drama,2016,615,7.1,8.0
3,3,Judwaa 2,Varun Dhawan,Comedy/Action,2017,227,3.6,4.0
4,4,Toilet: Ek Prem Katha,Akshay Kumar,Drama/Comedy,2017,311,7.2,11.0
5,5,Simmba,Ranveer Singh,Action/Comedy,2018,400,5.8,7.0
6,6,Sanju,Ranbir Kapoor,Biography,2018,586,7.6,2.0
7,7,Raazi,Alia Bhatt,Thriller/Drama,2018,195,7.7,13.0
8,8,Badhaai Ho,Ayushmann Khurrana,Comedy/Drama,2018,221,7.9,9.0
9,9,War,Hrithik Roshan,Action/Thriller,2019,475,6.5,5.0
10,10,Kabir Singh,Shahid Kapoor,Romance/Drama,2019,379,7.0,8.0
11,11,Mission Mangal,Akshay Kumar,Drama/Sci-Fi,2019,290,7.1,9.0
12,12,Tanhaji,Ajay Devgn,Historical/Action,2020,367,7.5,12.0
13,13,Bhool Bhulaiyaa 2,Kartik Aaryan,Horror/Comedy,2022,266,6.8,3.0
14,14,Gadar 2,Sunny Deol,Action/Drama,2023,691,5.1,6.0
15,15,Animal,Ranbir Kapoor,Action/Drama,2023,917,6.3,1.0
16,16,Jawan,Shah Rukh Khan,Action/Thriller,2023,1148,7.0,14.0
17,17,Stree 2,Rajkummar Rao,Horror/Comedy,2024,852,6.9,10.0
18,18,Chhaava,Vicky Kaushal,Historical/Drama,2025,808,7.3,15.0

In [70]:
cols = ["film"] + [col for col in df2.columns if col != "film"]
df2 = df2[cols]

In [71]:
df2

,film,index,actor,gener,saal,eraning,IMDB,Ranking
0,PK,0,Aamir Khan,Comedy/Sci-Fi,2014,750,8.1,16.0
1,Bajrangi Bhaijaan,1,Salman Khan,Drama/Action,2015,922,8.1,16.0
2,Sultan,2,Salman Khan,Sports/Drama,2016,615,7.1,8.0
3,Judwaa 2,3,Varun Dhawan,Comedy/Action,2017,227,3.6,4.0
4,Toilet: Ek Prem Katha,4,Akshay Kumar,Drama/Comedy,2017,311,7.2,11.0
5,Simmba,5,Ranveer Singh,Action/Comedy,2018,400,5.8,7.0
6,Sanju,6,Ranbir Kapoor,Biography,2018,586,7.6,2.0
7,Raazi,7,Alia Bhatt,Thriller/Drama,2018,195,7.7,13.0
8,Badhaai Ho,8,Ayushmann Khurrana,Comedy/Drama,2018,221,7.9,9.0
9,War,9,Hrithik Roshan,Action/Thriller,2019,475,6.5,5.0
10,Kabir Singh,10,Shahid Kapoor,Romance/Drama,2019,379,7.0,8.0
11,Mission Mangal,11,Akshay Kumar,Drama/Sci-Fi,2019,290,7.1,9.0
12,Tanhaji,12,Ajay Devgn,Historical/Action,2020,367,7.5,12.0
13,Bhool Bhulaiyaa 2,13,Kartik Aaryan,Horror/Comedy,2022,266,6.8,3.0
14,Gadar 2,14,Sunny Deol,Action/Drama,2023,691,5.1,6.0
15,Animal,15,Ranbir Kapoor,Action/Drama,2023,917,6.3,1.0
16,Jawan,16,Shah Rukh Khan,Action/Thriller,2023,1148,7.0,14.0
17,Stree 2,17,Rajkummar Rao,Horror/Comedy,2024,852,6.9,10.0
18,Chhaava,18,Vicky Kaushal,Historical/Drama,2025,808,7.3,15.0