In [1]:
import pandas as pd

In [2]:
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

In [3]:
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [4]:
departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [6]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [9]:
pd.merge(employees, departments , on="DeptID") # Inner join

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [10]:
pd.merge(employees, departments , on="DeptID" ,how="left" ) #Left join

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [11]:
pd.merge(employees, departments , on="DeptID" ,how="right" ) #Left join

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [12]:
pd.merge(employees, departments , on="DeptID" ,how="outer" ) #Outer join

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [19]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"], "score":[473,542]})
df1

    Name  score
0  Alice    473
1    Bob    542

In [20]:
df2 = pd.DataFrame({"Name": ["Charlie", "David"], "Age":[23,42]})
df2

      Name  Age
0  Charlie   23
1    David   42

In [21]:
pd.concat([df1 , df2]) # vertically

      Name  score   Age
0    Alice  473.0   NaN
1      Bob  542.0   NaN
0  Charlie    NaN  23.0
1    David    NaN  42.0

In [22]:
pd.concat([df1,df2], axis=1)

    Name  score     Name  Age
0  Alice    473  Charlie   23
1    Bob    542    David   42