In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data.csv")

In [3]:
df

,Actor,Film,Year,Genre,Boxoffice (Cr),IMDb
0,Aamir Khan,PK,2014,Comedy/Sci-Fi,750,8.1
1,Salman Khan,Bajrangi Bhaijaan,2015,Drama/Action,922,8.1
2,Shah Rukh Khan,Jawan,2023,Action/Thriller,1148,7.0
3,Ranbir Kapoor,Animal,2023,Action/Drama,917,6.3
4,Vicky Kaushal,Chhaava,2025,Historical/Drama,808,7.3
5,Rajkummar Rao,Stree 2,2024,Horror/Comedy,852,6.9
6,Sunny Deol,Gadar 2,2023,Action/Drama,691,5.1
7,Ranbir Kapoor,Sanju,2018,Biography,586,7.6
8,Salman Khan,Sultan,2016,Sports/Drama,615,7.1
9,Hrithik Roshan,War,2019,Action/Thriller,475,6.5
10,Shahid Kapoor,Kabir Singh,2019,Romance/Drama,379,7.0
11,Akshay Kumar,Mission Mangal,2019,Drama/Sci-Fi,290,7.1
12,Ajay Devgn,Tanhaji,2020,Historical/Action,367,7.5
13,Ranveer Singh,Simmba,2018,Action/Comedy,400,5.8
14,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror/Comedy,266,6.8
15,Varun Dhawan,Judwaa 2,2017,Comedy/Action,227,3.6
16,Alia Bhatt,Raazi,2018,Thriller/Drama,195,7.7
17,Akshay Kumar,Toilet: Ek Prem Katha,2017,Drama/Comedy,311,7.2
18,Ayushmann Khurrana,Badhaai Ho,2018,Comedy/Drama,221,7.9

In [4]:
df = df[df["IMDb"]>7.0]

In [5]:
df

,Actor,Film,Year,Genre,Boxoffice (Cr),IMDb
0,Aamir Khan,PK,2014,Comedy/Sci-Fi,750,8.1
1,Salman Khan,Bajrangi Bhaijaan,2015,Drama/Action,922,8.1
4,Vicky Kaushal,Chhaava,2025,Historical/Drama,808,7.3
7,Ranbir Kapoor,Sanju,2018,Biography,586,7.6
8,Salman Khan,Sultan,2016,Sports/Drama,615,7.1
11,Akshay Kumar,Mission Mangal,2019,Drama/Sci-Fi,290,7.1
12,Ajay Devgn,Tanhaji,2020,Historical/Action,367,7.5
16,Alia Bhatt,Raazi,2018,Thriller/Drama,195,7.7
17,Akshay Kumar,Toilet: Ek Prem Katha,2017,Drama/Comedy,311,7.2
18,Ayushmann Khurrana,Badhaai Ho,2018,Comedy/Drama,221,7.9

In [7]:
df.to_csv("data_updateIndex.csv", index=False)

# With Excel

In [12]:
df = pd.read_excel("data.xlsx")

In [13]:
df

       Name  School  Marks
0   shubham     PPY     55
1  manjeet      JJK     44
2    nikhil    JJHF     79
3    sumit      KDF     48
4     manas    KJFJ     35
5   saurabh  KJEFEF     95

In [15]:
data  = [
  {"id": 1, "name": "Astra", "role": "Navigator", "active": "true"},
  {"id": 2, "name": "Echo", "role": "Communications", "active": "false"},
  {"id": 3, "name": "Nova", "role": "Engineer", "active": "true"},
  {"id": 4, "name": "Orion", "role": "Pilot", "active": "true}
]

NameError: name 'true' is not defined